ecommerceproject/accounts/urls.py
from django.urls import path
from . import views
app_name='accounts'
urlpatterns=[
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

ecommerceproject/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('cart_remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

ecommerceproject/ecommerceapp/urls.py
from django.urls import path
from.import views
app_name='ecommerceapp'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
    ]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerceapp/',include('ecommerceapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('accounts/',include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerceproject/search_app/urls.py
from django.urls import path
from . import views
app_name="search_app"
urlpatterns=[
    path('search',views.SearchResult,name='SearchResult'),
]

ecommerceproject/cart/models.py
from django.db import models
from ecommerceapp.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price*self.quantity
    def __str__(self):
        return self.product

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect,get_object_or_404
from ecommerceapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity+=1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
        try:
            cart=Cart.objects.get(cart_id=_cart_id(request))
            cart_items=CartItem.objects.filter(cart=cart)
            for cart_item in cart_items:
                total+=(cart_item.product.price*cart_item.quantity)
                counter+=cart_item.quantity
        except ObjectDoesNotExist:
            pass
        return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
            <link rel="stylesheet" href="{% static 'css/custom.css' %}">
            <script src="https://kit.fontawesome.com/a076d05399.js"></script>

<body>
<div>
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% endblock %}
{% block title %}
Praravi-E Mart- Shop Your Favourite !!!!
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-centre">
        <h1 class="text-center">
            Your Cart is Empty!
        </h1>
        <br>
        <p class="text-centre">
            Please click <a href="{% url 'ecommerceapp:allProdCat' %}">Here</a>
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <h1 class="text-center">
            Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-centre">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src={{cart_item.product.image.url}} class="float-left rounded custom_image" style="width:50px;height:50px"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU:{{cart_item.product.id}}
                    <br>
                    Unit Price:{{cart_item.product.price}}
                    QTY:{{cart_item.quantity}}*₹{{cart_item.product.price}}
                </td>
                <td>{{cart_item.sub_total}}</td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a" ><i class="fas fa-plus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a" ><i class="fas fa-minus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a" ><i class="fas fa-minus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please Review Your Shopping Cart Items Before Proceeding With The Order Payment
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your total is <strong>{{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ecommerceapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
        </div>
    </div>
</div>
            <br>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
    {{ category.desc |truncatewords:155 }}
{% else %}
    Welcome to the Cart Store where You can Buy Awesome Items.
{% endif %}
{% endblock%}
{% block title %}
{% if category %}
    {{category.name}}-Shop Cart
{% else %}
    See Our Collections -Shop Cart
{% endif %}
{% endblock %}
{% block content %}
{% if category %}
    <div class="row my_row_class">
        <div class="mx-auto">
            <p><a href="{% url 'ecommerceapp:allProdCat' %}">our product collections </a>{{category.name}}</p>
        </div>
    </div>
{% endif %}
    <div class="auto-mx">
        {% if category %}
            <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
    </div><br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.desc}}</p>
    </div>
{% else %}
    <div>
        <center> <img class="my_image my_image_padding" src="{% static 'img/banner.jpg' %}" style="width:1120px;" alt="{{category.name}}"> </center>
    </div><br>
<div>
    <h1 class="text-center my_title">Our Products Collections</h1>
    <p class="text justify">We do not mass-produce any of our range, but operate a batch process system. This means that all our items are made with that bit more care and love - and you can see that in the finished item!</p>
</div>
{% endif %}
    <div class="container">
        <div class="row max-auto">
            {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 cpl-md-4 col-lg-4">
            <div class="card" style="width: 18rem;">
                <a href="{{product.get_url}}" ><img class="card-img-top my_image" src="{{product.image.url}}" style="width:250px;height:250px;" alt="{{product.name}}"> </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>₹{{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
        <div class="text-center">
        <div class="mx-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>

</div>
    </div>
{% endblock %}

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy;praravi Co-Ltd. All Rights Reserved</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<div>
    <center>
        <img src="{% static 'img/logos.gif' %}"alt="this is logo">
    </center>
</div>

ecommerceproject/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% endblock %}
{% block title %}
Praravi-E Mart- Shop Your Favourite !!!!
{% endblock %}
{% block content %}
<form action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username">
    <input type="password" name="password" placeholder="password">
    <input type="submit" value="login">
</form>
<div>
    {% for message in messages %}
    <h4>{{message}}</h4>
</div>
{% endfor %}
{% endblock %}

ecommerceproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% if user.is_authenticated %}
    <li><b>HI {{user.username}}</b></li>
  <a class="navbar-brand" href="{% url 'accounts:logout' %}">Logout</a>
    {% else %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:login' %}">Login <span class="sr-only">(current)</span></a>
      </li>
         <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:register' %}">Register <span class="sr-only">(current)</span></a>
      </li>
         {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart">{{item_count}}</i></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <a class="dropdown-item" href="{% url 'ecommerceapp:allProdCat' %}">All Products</a>
             <div class="dropdown-divider"></div>
            {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          <div class="dropdown-divider"></div>
            {% endfor %}
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
        </div>
   {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link disabled" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart">{{item_count}}</i></a>
      </li>
        {% endif %}
    </ul>
    <form  class="form-inline my-2 my-lg-0" action="{% url 'search_app:SearchResult' %}" method="get" >
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>
<!--<nav>-->
<!--    <ul>-->
<!--        <li> <a href="{% url 'ecommerceapp:allProdCat' %}">All Products</a> </li>-->
<!--        {% for cat in links %}-->
<!--        <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>-->
<!--        {% endfor %}-->
<!--    </ul>-->
<!--</nav><br>-->

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc |truncatewords:155}}
{% endblock %}
{% block title %}
    {{product.name}}-Shop Cart
{% endblock %}
    {% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'ecommerceapp:allProdCat' %}">Home</a> |<a href="{{product.category.get_url}}">{{product.name}}</a> </p>
    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width:18rem;">
                <img src="{{product.image.url}}" style="width:450px;height:450px" alt="{{product.name}}">
            </div>
        </div>
        <div class="col-12 col-sm-12 md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title">{{product.name}}</h1>
                <p>{{product.price}}</p>
                <p class="my_title">Product Description</p>
                <p class="text-justify">{{product.desc}}</p>
                {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}"> Add to Cart </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
    {% endblock %}

ecommerceproject/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% endblock %}
{% block title %}
Praravi-E Mart- Shop Your Favourite !!!!
{% endblock %}
{% block content %}
<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
    <input type="text" name="first_name" placeholder="firstname"><br>
    <input type="text" name="last_name" placeholder="lastname"><br>
    <input type="text" name="email" placeholder="email"><br>
    <input type="password" name="password1" placeholder="password"><br>
    <input type="password" name="password2" placeholder="password"><br>
    <input type="submit" value="registration">

</form>
<div>
    {% for message in messages %}
    <h4>{{message}}</h4>
</div>
    {% endfor %}
{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc |truncatewords:155}}
{% endblock %}
{% block title %}
    {{product.name}}-Shop Cart
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have Searched for:{{query}}</p>
</div>
 <div class="container">
        <div class="row max-auto">
            {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 cpl-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" style="width:250px;height:250px;" alt="{{product.name}}"> </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>₹{{product.price}}</p>
                </div>
            </div>
        </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">0 Results Found !</p>
            </div>
        {% endfor %}

       </div>
 </div>
{% endblock %}